// File generated by Blink v0.14.15 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const stepReplication: () => void
export declare const spawnOnClient: {
	fire: (Player: Player, Value: { serverId: number, serializedComponents: unknown }) => void
	fireAll: (Value: { serverId: number, serializedComponents: unknown }) => void
	fireExcept: (Except: Player, Value: { serverId: number, serializedComponents: unknown }) => void
	fireList: (List: Player[], Value: { serverId: number, serializedComponents: unknown }) => void
}
export declare const despawnOnClient: {
	fire: (Player: Player, Value: { serverId: number }) => void
	fireAll: (Value: { serverId: number }) => void
	fireExcept: (Except: Player, Value: { serverId: number }) => void
	fireList: (List: Player[], Value: { serverId: number }) => void
}
export declare const sendUnitPosition: {
	fire: (Player: Player, Value: { serverId: number, x: number, y: number, z: number, orientation: number }) => void
	fireAll: (Value: { serverId: number, x: number, y: number, z: number, orientation: number }) => void
	fireExcept: (Except: Player, Value: { serverId: number, x: number, y: number, z: number, orientation: number }) => void
	fireList: (List: Player[], Value: { serverId: number, x: number, y: number, z: number, orientation: number }) => void
}
export declare const requestMovement: {
	on: (Listener: (Player: Player, Value: { serverIds: number[], x: number, z: number, increment: boolean }) => void) => (() => void)
}
export declare const spawnUnitCmd: {
	on: (Listener: (Player: Player, Value: { x: number, z: number }) => void) => (() => void)
}
